# TODO
# - Wait for 3D model
# - Check sensors (Nav Radar, Bass Tilt)
# - Add full CIWS functionality
# - Effects
#   - Sounds
#   - Particles
# - Colliders

[---------- General Data ----------]
[General]
UnitType=Vessel
DefaultCameraDistance=1.5
MinCameraDistanceForeAft=0.0 # 0.8
MinCameraDistanceBroadside=0.0 # 0.5
CameraPivotHeight=0.09

Length=57.3                    // in meters
Beam=25.6                       // in meters

CompartmentsHeight=0.05        // Governs bouyancy compartment height and also missile aimpoint
ArmorType=None

[Physics]
#all damping values can go from 0 (max damping) up to 1 (no damping)
Displacement=550               // in tons

MaxForwardVelocity=60          // sets the max forward velocity
MaxBackwardVelocity=30          // sets the max backward velocity
LinearDrag=0.9                // this is for velocity damping (linear drag)
MaxAccelerationFactor=1.8
MinAccelerationFactor=0.4

RudderTurnRate=5.0             // turn rate of the rudder in degrees per second
RudderForce=0.8                // multiplicator defining how agile the ship can turn

TiltFactor=-1.0                 // defines how strong the tilting will be
PitchFactor=3.0                // defines how strong the pitch will be based on speed and acceleration

TrimDepth=0                  // default trim depth in feet
TrimAngle=0                  // default base trim angle (x-axis, so pitch)
CenterToKeelDist=0           // distance from the center of the mesh to the keel in Unity units

[Buoyancy]
Density=0.5                    // density of water is 1. Density < 1 means it will swim
OutOfWaterDrag=25.0             // drag for the water physics in case the vessel is above the water line
SubmergedDrag=25.0             // drag for the water physics in case the vessel is below the water line

[SensorData]
#Visual
VisualIdentificationRange=6   // Biggest range in nm at which this unit can be visually identified
IRSignature=SemiSmall
# Radar related (RCS => radar cross section)
RCS=SemiSmall
# Sonar related
BaseNoise=160                   // base sound level in db at 1m distance
FlowNoise=1                     // additional flow noise per knot in db (20kn would be +20db)
CavitationNoise=5               // additional noise for cavitation in db
BladesCount=3					 //number of blades on vessels propulsion systems
MinNoiseClassificationTreshold=3 //in dBs, the minimal value of noise on sonar system to begin classification/identification process of this vessel
ElectricFrequency=60             //in Hz, typical values 50 or 60, 400 for Soviet Alfa class SSN

[---------- AI related ----------]
[AI]
UnitCostValue=100            // value for the unit cost for least valuable target checks
UnitScoreValue=1              // value for calculation of mission score

#Sensors
Radar_Capability=TBD
Sonar_Capability=TBD
AirRecon_Capability=TBD

#Offence
AAW_Capability=
ASuW_Capability=
ASW_Capability=

#Defence
MissilesToSaturate=1      //AI will try to shoot missiles with this SaturationValue combined to kill this target
TorpedoesToSaturate=1     //AI will try to shoot torpedoes with this SaturationValue combined to kill this target

AMD_Capability=TBD    //Anti-Missile Defence
ATD_Capability=TBD      //Anti-Torpedo Defence

#Special
Role=Spy

[---------- Main Systems ----------]
[MainPowerSystem]
Type=Diesel
HorsePower=30000

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=3
#---------- Visual ----------
[SensorSystem1] #Bridge
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0,0.113,-0.0277

# AK-630 FCR
[SensorSystem2] #Bass_Tilt
Type=Radar
SystemName=Bass_Tilt
Mount=Bass_Tilt_1
RestAngles=0
Collider=coll_bass_tilt

[SensorSystem3] #Nav Radar
Type=Radar
SystemName=Nav_Radar
Mount=Nav_Radar_1

[---------- Weapon Systems ----------]
[WeaponSystems]
NumberOfWeaponSystems=1

[WeaponSystem1]  #CIWS left
Type=CIWS
SystemName=AK630
#Sensors
AssociatedSensors=SensorSystem2
#Animations
#Mount
Mount=AK630_left
IsMountRotatable=True
#Containers
ContainerBase=AK630_left_barrel
Gun=AK630_left_barrel
AreContainersRotatable=True
#Angles
FiringArcs=10,-35
ElevationArc=-15,85
RestAngles=180
#Loading
Ammunition=wp_cal_30mm
#Effects
#Other
WorksStandalone=True
Collider=coll_ak630

[---------- WeaponMagazines ----------]
[WeaponMagazine_CWIS]
NumberOfAmmunitionTypes=1
Ammunition1=wp_cal_30mm
Ammunition1_Count=2000
ModuleType=SmallMagazine

[--------------------------- Mesh definitions ---------------------------]
[Models]

ResourcesFolder=assets/
ResourcesRoot=wp_zubr.obj
ResourcesMesh=Hull
ResourcesMaterial=wp_zubr_mat.ini

[Submodels]
SubModel1=Hull2
SubModel2=Cushion
SubModel3=MLRS_Bay
SubModel4=Superstructure
SubModel5=CIWS_Base
SubModel6=Parts

# Sensors
SubModel9=Bass_Tilt_1
SubModel10=Nav_Radar_1

# CWIS
SubModel7=AK630_left
SubModel8=AK630_left_barrel

[Hull2]
Mesh=Hull_2
Material=wp_zubr_mat.ini

[Cushion]
Mesh=Cushion
Material=wp_zubr_mat.ini

[Cushion]
Mesh=Cushion
Material=wp_zubr_mat.ini

[MLRS_Bay]
Mesh=MLRS_Bay
Material=wp_zubr_mat.ini

[Superstructure]
Mesh=Superstructure
Material=wp_zubr_mat.ini

[CIWS_Base]
Mesh=CIWS_Base
Material=wp_zubr_mat.ini

[Parts]
Mesh=Parts
Material=wp_zubr_mat.ini

### Sensors ###

[Bass_Tilt_1] # CWIS FCR
ResourcesMeshFolder=ships/wp_mpk_grisha3/
ResourcesRoot=wp_mpk_grisha3
RootMesh=wp_mpk_grisha3
Mesh=wp_mpk_grisha3_basstilt
ResourcesMaterialFolder=ships/materials/
ResourcesMaterial=wp_mpk_grisha3_mat
Material=modular_parts
Position=0.00,0.1307,-0.0445
Rotation=0,0,0

[Nav_Radar_1] # Nav Radar
ResourcesMeshFolder=ships/civ_ms_metallurg_anosov/
ResourcesRoot=civ_ms_metallurg_anosov
RootMesh=civ_ms_metallurg_anosov
Mesh=civ_ms_metallurg_anosov_surfacesearch
ResourcesMaterialFolder=ships/civ_ms_metallurg_anosov/
ResourcesMaterial=civ_ms_metallurg_anosov_mat
Material=civ_ms_metallurg_anosov_mat
Position=0,0.245,0.013
Rotation=0,0,0

### Weapons ###

[AK630_left]
ResourcesMeshFolder=ships/wp_mpk_grisha3/
ResourcesRoot=wp_mpk_grisha3
RootMesh=wp_mpk_grisha3
Mesh=wp_mpk_grisha3_AK630
ResourcesMaterialFolder=ships/materials/
ResourcesMaterial=wp_mpk_grisha3_mat
Material=modular_parts
Parent=VisibleParent
Position=-0.061953,0.080313,0.110949
Rotation=0,0,0

[AK630_left_barrel]
ResourcesMeshFolder=ships/wp_mpk_grisha3/
ResourcesRoot=wp_mpk_grisha3
RootMesh=wp_mpk_grisha3
Mesh=wp_mpk_grisha3_AK630_barrel
ResourcesMaterialFolder=ships/materials/
ResourcesMaterial=wp_mpk_grisha3_mat
Material=modular_parts
Parent=AK630_left
Position=0,0.0045,0
Rotation=0,0,0

[---------- Effects ----------]

[Foam]
HullFoamTexture=ships/particles/wake/Ceto_Hullwake
HullFoamPosition=0,0,0.2
HullFoamDuration=10
HullFoamSize=0.3
HullFoamSpacing=0.1
HullFoamExpansion=0.055
HullFoamMomentum=0
HullFoamSpin=0
HullFoamAlpha=2
HullFoamJitter=0.25