[General]
UnitType=Vessel
DefaultCameraDistance=1.25
MinCameraDistanceForeAft=0.35
MinCameraDistanceBroadside=0.35
CameraPivotHeight=0.1

Length=57                          
Beam=25.6

// Hull armor: None, Minor, Moderate, Heavy
ArmorType=None

[---------- Physics and Control ----------]
[Physics]
Displacement=550                      
MaxForwardVelocity=63.0
MaxBackwardVelocity=15.0
TelegraphVelocities=-15,0,10,30,55,63

LinearDrag=0.85
MaxAccelerationFactor=0.8
MinAccelerationFactor=0.1

RudderTurnRate=7.5
RudderForce=0.8

[Buoyancy]
Density=0.5
OutOfWaterDrag=25.0

[SensorData]
#Visual
VisualIdentificationRange=5.0
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Medium                              
# Sonar related
BaseNoise=135                           
FlowNoise=1.1
CavitationNoise=25
TargetReflectionStrength=22             
BladesCount=5                           
ElectricFrequency=60                    
DistinctiveNoise=False


[---------- Mesh definitions----------]
[Models]
LODLevels=1
LOD1Distance=5.0

ResourcesFolder=model/
ResourcesRoot=wp_zubr.obj
ResourcesMesh=Cube
